import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import path from 'node:path';
const photo=path.resolve('public/icons/icon-512.png');
async function add(page:Page,title:string,withPhoto=false){await page.getByRole('button',{name:/^(New note|Add note)$/}).filter({visible:true}).click();await page.getByLabel('Title *',{exact:true}).fill(title);if(withPhoto){await page.locator('input[type=file]').setInputFiles(photo);await page.getByRole('button',{name:'Use photo',exact:true}).click();await expect(page.getByRole('dialog',{name:'Adjust photo'})).toBeHidden();}await page.getByRole('button',{name:'Save note',exact:true}).click();await page.getByRole('button',{name:'All notes',exact:true}).click();}
async function edit(page:Page,title:string,next:string){await page.getByRole('button').filter({has:page.getByRole('heading',{name:title,exact:true})}).click();await page.getByRole('button',{name:'Note actions'}).click();await page.getByRole('menuitem',{name:'Edit note',exact:true}).click();await page.getByLabel('Title *',{exact:true}).fill(next);await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('button',{name:'All notes',exact:true}).click();}
test('login automatically merges old device collections and propagates live create edit delete',async({browser})=>{
 test.setTimeout(150000);
 const phone=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),desktop=await browser.newContext({viewport:{width:1280,height:850}});const p=await phone.newPage(),d=await desktop.newPage();
 await p.goto('/');await d.goto('/');await add(p,'Old phone memory',true);await add(d,'Old desktop memory');
 const owner=`auto-${crypto.randomUUID()}`,headers={'oai-authenticated-user-id':owner,'oai-authenticated-user-email':'same-account@sites.test'};
 await phone.setExtraHTTPHeaders(headers);await desktop.setExtraHTTPHeaders(headers);
 const upload=p.waitForResponse(r=>r.url().endsWith('/api/sync')&&r.request().method()==='POST'&&r.ok(),{timeout:10000});await p.reload();await upload;
 await d.reload();await expect(d.getByRole('heading',{name:'Old phone memory',exact:true})).toBeVisible();await expect(d.getByRole('heading',{name:'Old desktop memory',exact:true})).toBeVisible();await expect(p.getByRole('heading',{name:'Old desktop memory',exact:true})).toBeVisible({timeout:25000});
 await add(p,'New phone memory');await expect(d.getByRole('heading',{name:'New phone memory',exact:true})).toBeVisible({timeout:25000});await add(d,'New desktop memory');await expect(p.getByRole('heading',{name:'New desktop memory',exact:true})).toBeVisible({timeout:25000});
 await edit(p,'New phone memory','Edited on phone');await expect(d.getByRole('heading',{name:'Edited on phone',exact:true})).toBeVisible({timeout:25000});await edit(d,'New desktop memory','Edited on desktop');await expect(p.getByRole('heading',{name:'Edited on desktop',exact:true})).toBeVisible({timeout:25000});
 await phone.setOffline(true);await edit(p,'Edited on phone','Offline edit');await phone.setOffline(false);await expect(d.getByRole('heading',{name:'Offline edit',exact:true})).toBeVisible({timeout:25000});
 await d.getByRole('button').filter({has:d.getByRole('heading',{name:'Edited on desktop',exact:true})}).click();await d.getByRole('button',{name:'Note actions'}).click();await d.getByRole('menuitem',{name:'Delete note',exact:true}).click();await d.getByRole('button',{name:'Delete note',exact:true}).click();await expect(p.getByRole('heading',{name:'Edited on desktop',exact:true})).toBeHidden({timeout:25000});
 await p.getByRole('button').filter({has:p.getByRole('heading',{name:'Old phone memory',exact:true})}).click();await expect(p.getByRole('img',{name:'Old phone memory, photo 1'})).toBeVisible();await phone.close();await desktop.close();
});
test('background sync failures remain visible, preserve local notes and recover on retry',async({browser})=>{
 const ctx=await browser.newContext({extraHTTPHeaders:{'oai-authenticated-user-id':`error-${crypto.randomUUID()}`,'oai-authenticated-user-email':'same-account@sites.test'}}),p=await ctx.newPage();
 await p.route('**/api/sync',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Temporary cloud failure'})}));await p.goto('/');await add(p,'Safe local note');await expect(p.locator('.sync-warning')).toContainText('Local notes are safe');await p.getByRole('button',{name:'Settings',exact:true}).click();await expect(p.getByText('Sync error · Local notes are safe',{exact:true})).toBeVisible();await p.unroute('**/api/sync');await p.getByRole('button',{name:'Sync now',exact:true}).click();await expect(p.getByText('Cloud backup is up to date',{exact:true})).toBeVisible();await ctx.setOffline(true);await expect(p.getByText('Offline · Changes will sync when connected',{exact:true})).toBeVisible();await p.getByRole('button',{name:'Collection',exact:true}).click();await expect(p.getByRole('heading',{name:'Safe local note',exact:true})).toBeVisible();await ctx.close();
});
