import {test,expect,type Page} from '@playwright/test';
import {THEME_IDS,THEMES} from '../../lib/themes';
async function seed(page:Page){await page.goto('/');await expect(page.getByRole('heading',{name:/All notes/})).toBeVisible();await page.evaluate(async()=>{const database=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('memorate',2);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const canvas=document.createElement('canvas');canvas.width=600;canvas.height=600;const c=canvas.getContext('2d')!;c.fillStyle='#789681';c.fillRect(0,0,600,600);c.fillStyle='#eee4cb';c.beginPath();c.arc(300,300,200,0,Math.PI*2);c.fill();const blob=await new Promise<Blob>(resolve=>canvas.toBlob(b=>resolve(b!),'image/jpeg'));
 const titles=['Sushi by the river','Babor cleanser','A very long title about the impossibly soft oversized cardigan I kept thinking about all winter and finally brought home','Crème brûlée'];
 await new Promise<void>(resolve=>{const tx=database.transaction('notes','readwrite');titles.forEach((title,i)=>tx.objectStore('notes').put({id:`gallery-${i}`,title,comment:i%2?'':'Lovely lunch by the river',rating:i===2?null:4,categoryId:i===1?'beauty':'food',date:'2026-09-25',price:null,currency:'EUR',createdAt:'2026-09-25T10:00:00.000Z',updatedAt:'2026-09-25T10:00:00.000Z',syncState:'local',barcode:i===1?'6901668054715':undefined,productInfo:i===1?{barcode:'6901668054715',brand:'Babor',ingredients:'Water and almond oil'}:undefined,photos:i===2?[]:Array.from({length:i===0?2:1},(_,j)=>({id:`photo-${i}-${j}`,blob,width:600,height:600}))}));tx.oncomplete=()=>resolve();});database.close();});await page.reload();await expect(page.locator('.note-card')).toHaveCount(4);}
async function share(page:Page){await page.getByRole('button',{name:'Note actions'}).click();await page.getByRole('menuitem',{name:'Share',exact:true}).click();}
test('gallery preserves search, filters, preference and details with all photo cases on mobile and desktop',async({page,context})=>{
 await seed(page);await page.getByRole('button',{name:'Gallery',exact:true}).click();await expect(page.locator('.gallery-card')).toHaveCount(4);await expect(page.locator('.without-photo')).toHaveCount(1);await expect(page.getByLabel('2 photos')).toHaveCount(1);await expect(page.locator('.gallery-cover img')).toHaveCount(3);
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const columns=await page.locator('.collection-gallery').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length);expect(columns).toBe(width<=700?2:3);}
 await page.getByLabel('Search notes').fill('suhsi');await expect(page.locator('.gallery-card')).toHaveCount(1);await page.locator('.gallery-card').click();await expect(page.locator('.detail-view h1')).toHaveText('Sushi by the river');await page.getByRole('button',{name:'All notes',exact:true}).click();await expect(page.locator('.detail-view')).toBeHidden();await page.getByLabel('Search notes').fill('babor almond');await expect(page.locator('.gallery-card h2')).toHaveText('Babor cleanser');await page.getByLabel('Search notes').fill('');await page.getByRole('button',{name:'Beauty',exact:true}).click();await expect(page.locator('.gallery-card')).toHaveCount(1);await page.reload();await expect(page.getByRole('button',{name:'Gallery',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.locator('.gallery-card')).toHaveCount(4);
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await context.setOffline(true);await page.getByLabel('Search notes').fill('creme');await expect(page.locator('.gallery-card h2')).toHaveText('Crème brûlée');await context.setOffline(false);
 await page.screenshot({path:'/tmp/memorate-gallery-desktop.png',fullPage:true});await page.getByLabel('Search notes').fill('');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/memorate-gallery-mobile.png',fullPage:true});
});
test('all themes apply immediately, persist and cover mobile dialogs and gallery',async({page})=>{
 await seed(page);await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Settings',exact:true}).click();for(const id of THEME_IDS){const name=id==='system'?'System':THEMES[id].name;await page.getByRole('button',{name,exact:true}).click();await expect(page.getByRole('button',{name,exact:true})).toHaveAttribute('aria-pressed','true');if(id!=='system')await expect(page.locator('html')).toHaveAttribute('data-theme',id);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
 await page.getByRole('button',{name:'Ocean',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','ocean');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','ocean');await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByRole('button',{name:'Ocean',exact:true})).toHaveAttribute('aria-pressed','true');await page.screenshot({path:'/tmp/memorate-themes-mobile.png',fullPage:true});await page.getByRole('button',{name:'Collection',exact:true}).click();await page.getByRole('button',{name:'Gallery',exact:true}).click();await page.getByRole('button',{name:'Add note',exact:true}).click();await expect(page.getByLabel('Title *',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Scan product',exact:true}).click();await expect(page.getByRole('button',{name:'Start camera',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close scanner',exact:true}).click();
});
test('share posters are real fixed-size PNGs for photo/no-photo, long/unrated and comment-free notes; fallback downloads',async({page})=>{
 await seed(page);for(const index of [0,1,2]){await page.locator('.note-card').nth(index).click();await share(page);await page.getByRole('button',{name:'Share as image',exact:true}).click();const preview=page.getByAltText('Share image preview');await expect(preview).toBeVisible();expect(await preview.evaluate((el:HTMLImageElement)=>[el.naturalWidth,el.naturalHeight])).toEqual([1080,1350]);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save image',exact:true}).click();const file=await download;expect(file.suggestedFilename()).toBe('memorate-note.png');if(index===2)await file.saveAs('/tmp/memorate-share-poster.png');await page.getByRole('dialog',{name:'Share note'}).getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'All notes',exact:true}).click();}
});
test('native image share receives a file and cancellation is harmless',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{value:()=>true});Object.defineProperty(navigator,'share',{value:async(data:ShareData)=>{document.documentElement.dataset.sharedFile=data.files?.[0]?.type;throw new DOMException('Cancelled','AbortError');}});});await seed(page);await page.locator('.note-card').first().click();await share(page);await page.getByRole('button',{name:'Share as image',exact:true}).click();await expect(page.getByAltText('Share image preview')).toBeVisible();await page.getByRole('button',{name:'Share image',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-shared-file','image/png');await expect(page.getByRole('dialog',{name:'Share note'}).getByRole('alert')).toHaveCount(0);
});
