import { test, expect } from '@playwright/test';
import type { CDPSession, Page } from '@playwright/test';
import path from 'node:path';
async function drag(cdp:CDPSession,x:number,y:number,dx:number,dy:number,mid?:()=>Promise<void>){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=10;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/10,y:y+dy*i/10}]});await new Promise(r=>setTimeout(r,20));}if(mid)await mid();await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
async function note(page:Page){await page.getByRole('button',{name:/^(New note|Add note)$/}).filter({visible:true}).click();await page.getByLabel('Title *',{exact:true}).fill('Memory with photo');await page.getByRole('button',{name:'4 stars',exact:true}).click();await page.getByLabel('Comment',{exact:true}).fill('Warm coffee and a quiet afternoon.');await page.getByLabel('Price',{exact:true}).fill('12,99');await page.getByLabel('Date',{exact:true}).fill('2026-09-24');await page.locator('input[type=file]').setInputFiles(path.resolve('public/icons/icon-512.png'));await page.getByRole('button',{name:'Use photo',exact:true}).click();await expect(page.getByRole('dialog',{name:'Adjust photo'})).toBeHidden();await page.getByRole('button',{name:'Save note',exact:true}).click();await page.getByRole('button',{name:'All notes',exact:true}).click();}
test('mobile sheet follows touch, cancels or dismisses, and edge-back preserves real navigation',async({browser})=>{
 const ctx=await browser.newContext({viewport:{width:390,height:650},hasTouch:true,isMobile:true});const p=await ctx.newPage();await p.goto('/');await note(p);const cdp=await ctx.newCDPSession(p);
 await p.getByRole('button',{name:'Filters and sort',exact:true}).click();await expect(p.locator('.filter-sheet')).toHaveCSS('translate','none');const box=(await p.getByRole('button',{name:'Close sheet'}).boundingBox())!;
 await drag(cdp,195,box.y+12,0,30);await expect(p.locator('.filter-sheet')).toBeVisible();await expect(p.locator('.filter-sheet')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');
 await drag(cdp,195,box.y+12,0,165,async()=>{const y=await p.locator('.filter-sheet').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m42);expect(y).toBeGreaterThan(100);});await expect(p.locator('.filter-sheet')).toBeHidden();
 await p.setViewportSize({width:390,height:500});await p.getByRole('button',{name:'Filters and sort',exact:true}).click();await expect(p.locator('.filter-sheet')).toHaveCSS('translate','none');await drag(cdp,190,330,0,-100);await expect.poll(()=>p.locator('.filter-scroll').evaluate(e=>e.scrollTop)).toBeGreaterThan(0);await p.getByLabel('From date').fill('2026-09-01');await expect(p.locator('.filter-sheet .date-display').first()).toContainText('2026');await p.getByRole('button',{name:'Close filters'}).click();await expect(p.locator('.filter-sheet')).toBeHidden();
 await p.setViewportSize({width:390,height:650});await p.locator('.note-card').click();await drag(cdp,8,220,35,0);await expect(p.locator('.detail-view')).toBeVisible();await expect(p.locator('.detail-surface')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');
 await drag(cdp,8,220,180,0,async()=>{expect(await p.locator('.detail-surface').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41)).toBeGreaterThan(140);});await expect(p.locator('.note-card')).toBeVisible();
 await p.locator('.note-card').click();await drag(cdp,180,240,80,0);await expect(p.locator('.detail-view')).toBeVisible();await drag(cdp,180,530,0,-160);await expect.poll(()=>p.evaluate(()=>scrollY)).toBeGreaterThan(0);await p.getByRole('button',{name:'All notes',exact:true}).click();await expect(p.locator('.note-card')).toBeVisible();await ctx.close();
});
test('mobile controls prevent focus autozoom and dates keep full years at narrow widths',async({browser})=>{
 const ctx=await browser.newContext({viewport:{width:320,height:740},hasTouch:true,isMobile:true});const p=await ctx.newPage();await p.goto('/');await p.getByRole('button',{name:'Add note',exact:true}).click();await p.getByRole('button',{name:'New category',exact:true}).click();
 for(const label of ['Title *','Comment','New category name','Price']){const field=p.getByLabel(label,{exact:true});expect(await field.evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBeGreaterThanOrEqual(16);await field.fill(label==='Price'?'2,5':'QA');await field.press('Tab');expect(await p.evaluate(()=>visualViewport?.scale)).toBe(1);}
 await p.getByLabel('Date',{exact:true}).fill('2026-09-24');await expect(p.locator('.date-display')).toContainText('2026');for(const width of [320,375,390,430]){await p.setViewportSize({width,height:740});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
 await p.getByRole('button',{name:'Close',exact:true}).click();await p.getByRole('button',{name:'Discard changes',exact:true}).click();expect(await p.getByRole('searchbox').evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBeGreaterThanOrEqual(16);await p.getByRole('searchbox').fill('test');await p.getByRole('searchbox').press('Tab');expect(await p.evaluate(()=>visualViewport?.scale)).toBe(1);await ctx.close();
});
test('desktop drawer direction, dismissals and editorial hover keep cards stable',async({page})=>{
 await page.setViewportSize({width:1440,height:900});await page.goto('/');await note(page);const card=page.locator('.note-card');await expect(card.locator('.card-metadata .card-date')).toContainText('2026');await expect(card.locator('.card-top .card-date')).toHaveCount(0);
 await card.hover();const star=card.locator('.rating-mark');expect(await star.evaluate(e=>getComputedStyle(e).animationDuration)).toBe('0.56s');expect(await star.evaluate(e=>getComputedStyle(e).animationIterationCount)).toBe('1');await expect(card).toHaveCSS('transform','none');await expect(card).toHaveCSS('box-shadow','none');
 await expect.poll(()=>card.locator('.card-photo-frame').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).b)).toBeGreaterThan(.01);const matrix=await card.locator('.card-photo-frame').evaluate(e=>{const m=new DOMMatrix(getComputedStyle(e).transform);return Math.hypot(m.a,m.b);});expect(matrix).toBeCloseTo(1,3);await expect(card.locator('.card-photo')).toHaveCSS('transform','none');
 await page.getByRole('button',{name:'Filters and sort',exact:true}).click();await expect(page.locator('.filter-sheet')).toHaveCSS('animation-name','drawer-in');const box=(await page.locator('.filter-sheet').boundingBox())!;expect(box.width).toBeGreaterThanOrEqual(360);expect(box.width).toBeLessThanOrEqual(440);await expect(page.getByRole('button',{name:'Close sheet'})).toBeHidden();await page.keyboard.press('Escape');await expect(page.locator('.filter-sheet')).toBeHidden();
 await page.getByRole('button',{name:'Filters and sort',exact:true}).click();await page.locator('[data-slot="sheet-overlay"]').click({position:{x:100,y:100}});await expect(page.locator('.filter-sheet')).toBeHidden();
 await page.emulateMedia({reducedMotion:'reduce'});await card.hover();await expect(star).toHaveCSS('animation-name','none');
});
