import {test,expect} from '@playwright/test';
test('detail swipe reveals the mounted collection at its saved position, cancels and completes; reduced motion back works',async({browser})=>{
 const ctx=await browser.newContext({viewport:{width:390,height:650},hasTouch:true,isMobile:true});const page=await ctx.newPage();await page.goto('/');await expect(page.getByRole('heading',{name:/All notes/})).toBeVisible();
 await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>(resolve=>{const r=indexedDB.open('memorate',2);r.onsuccess=()=>resolve(r.result);});await new Promise<void>(resolve=>{const tx=db.transaction('notes','readwrite');for(let i=0;i<20;i++)tx.objectStore('notes').put({id:`layer-${i}`,title:`Layer note ${i}`,categoryId:'food',rating:4,date:'2026-09-25',comment:'A memory',price:3,currency:'EUR',createdAt:'',updatedAt:'',photos:[],syncState:'local'});tx.oncomplete=()=>resolve();});});await page.reload();await page.getByRole('searchbox').fill('Layer');await page.getByRole('button',{name:'Food',exact:true}).click();await page.evaluate(()=>scrollTo(0,600));
 const origin=await page.locator('.home-view').evaluate(e=>e.getBoundingClientRect().top);const visibleIndex=await page.locator('.note-card').evaluateAll(cards=>cards.findIndex(e=>{const r=e.getBoundingClientRect();return r.top>60&&r.bottom<innerHeight;}));expect(visibleIndex).toBeGreaterThanOrEqual(0);const target=page.locator('.note-card').nth(visibleIndex);await target.click();await expect(page.locator('.detail-view')).toBeVisible();await expect(page.locator('.detail-surface')).toHaveCSS('translate','none');await expect(page.locator('.collection-layer')).toHaveAttribute('inert','');expect(await page.locator('.home-view').evaluate(e=>e.getBoundingClientRect().top)).toBe(origin);
 const cdp=await ctx.newCDPSession(page);const drag=async(distance:number)=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:8,y:220}]});for(let i=1;i<=6;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:8+distance*i/6,y:220}]});};
 await drag(35);expect(await page.locator('.detail-surface').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41)).toBeGreaterThan(20);expect(await page.locator('.home-view').evaluate(e=>e.getBoundingClientRect().top)).toBe(origin);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect(page.locator('.detail-surface')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');
 await drag(190);expect(await page.locator('.detail-surface').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41)).toBeGreaterThan(150);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect(page.locator('.detail-view')).toBeHidden();await expect.poll(()=>page.evaluate(()=>scrollY)).toBe(600);await expect(page.getByRole('searchbox')).toHaveValue('Layer');await expect(page.getByRole('button',{name:'Food',exact:true})).toHaveClass(/selected/);
 await page.emulateMedia({reducedMotion:'reduce'});await target.click();await page.getByRole('button',{name:'All notes',exact:true}).click();await expect(page.locator('.detail-view')).toBeHidden();await expect.poll(()=>page.evaluate(()=>scrollY)).toBe(600);await ctx.close();
});
