import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
import path from 'node:path';
const barcode='3017620422003';
async function openScanner(page:Page){await page.goto('/');await page.getByRole('button',{name:'Scan product',exact:true}).click();await expect(page.getByRole('dialog',{name:'Scan product',exact:true})).toBeVisible();}
async function known(page:Page,photo=true){await page.route(`**/api/products/${barcode}?*`,r=>r.fulfill({json:{product:{barcode,name:'Hazelnut spread',source:'open-food-facts',hasImage:photo}}}));await page.route(`**/api/products/${barcode}/image?*`,r=>r.fulfill({path:path.resolve('public/icons/icon-512.png'),contentType:'image/png'}));}
test('manual lookup prefills editable title/photo, saves barcode and photo offline, detects existing product',async({page,context})=>{
 await known(page);await openScanner(page);await page.getByLabel('Barcode number').fill(barcode);await page.getByRole('button',{name:'Find product',exact:true}).click();await expect(page.getByLabel('Title *',{exact:true})).toHaveValue('Hazelnut spread');await expect(page.getByRole('button',{name:'Remove photo 1'})).toBeVisible();await page.getByLabel('Title *',{exact:true}).fill('My hazelnut spread');await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.locator('.detail-view')).toContainText('My hazelnut spread');await page.getByRole('button',{name:'All notes',exact:true}).click();await expect(page.locator('.detail-view')).toBeHidden();
 await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByRole('button',{name:'Scan product',exact:true}).click();await page.getByLabel('Barcode number').fill(barcode);await page.getByRole('button',{name:'Find product',exact:true}).click();await expect(page.getByText(/already added this product/)).toBeVisible();await page.getByRole('button',{name:'Open existing note',exact:true}).click();await expect(page.locator('.detail-view')).toContainText('My hazelnut spread');
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await page.reload();await page.locator('.note-card').click();await expect(page.locator('.detail-view img').first()).toBeVisible();expect(await page.locator('.detail-view img').first().evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true);
 const saved=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>(resolve=>{const r=indexedDB.open('memorate',2);r.onsuccess=()=>resolve(r.result);});return await new Promise<{barcode:string}[]>(resolve=>{const r=db.transaction('notes').objectStore('notes').getAll();r.onsuccess=()=>resolve(r.result);});});expect(saved[0].barcode).toBe(barcode);
});
test('product photo can be removed and replaced; unknown and network errors permit manual notes',async({page})=>{
 await known(page);await openScanner(page);await page.getByLabel('Barcode number').fill(barcode);await page.getByRole('button',{name:'Find product',exact:true}).click();await page.getByRole('button',{name:'Remove photo 1'}).click();await expect(page.locator('.photo-edit')).toHaveCount(0);await page.locator('input[type=file]').setInputFiles(path.resolve('public/icons/icon-512.png'));await page.getByRole('button',{name:'Use photo',exact:true}).click();await expect(page.locator('.photo-edit')).toHaveCount(1);
 await page.getByRole('button',{name:'Scan product',exact:true}).click();await page.route('**/api/products/96385074?*',r=>r.fulfill({json:{product:null}}));await page.getByLabel('Barcode number').fill('96385074');await page.getByRole('button',{name:'Find product',exact:true}).click();await expect(page.getByText('Product not found',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Scan again',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Enter barcode manually',exact:true})).toBeVisible();await page.getByRole('button',{name:'Enter product manually',exact:true}).click();await expect(page.getByText('Product not found. Add the details yourself.')).toBeVisible();await expect(page.getByLabel('Title *',{exact:true})).toHaveValue('Hazelnut spread');
 await page.getByRole('button',{name:'Scan product',exact:true}).click();await page.route('**/api/products/96385074?*',r=>r.fulfill({status:503,json:{error:'unavailable'}}));await page.getByLabel('Barcode number').fill('96385074');await page.getByRole('button',{name:'Find product',exact:true}).click();await expect(page.getByRole('alert')).toContainText('unavailable');await page.getByRole('button',{name:'Continue manually',exact:true}).click();await expect(page.getByLabel('Title *',{exact:true})).toBeVisible();
});
test('camera denial is recoverable and no camera is requested before Start camera',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{document.documentElement.dataset.cameraRequested='yes';throw new DOMException('Denied','NotAllowedError');}});});await openScanner(page);expect(await page.locator('html').getAttribute('data-camera-requested')).toBeNull();await page.getByRole('button',{name:'Start camera'}).click();await expect(page.getByRole('alert')).toContainText('denied');await page.getByLabel('Barcode number').fill('96385074');await page.getByRole('button',{name:'Continue manually'}).click();await expect(page.getByText('Barcode: 96385074')).toBeVisible();
});
test('real ZXing EAN decoding from a camera stream stops tracks after success and cancel',async({page})=>{
 // EAN-13 fixture for 3017620422003, with 3's LLGGGL parity.
 const left=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'];
 const parity='LLGGGL';const digits=barcode.slice(1).split('').map(Number);const invert=(s:string)=>s.replace(/[01]/g,b=>b==='1'?'0':'1');
 const pattern='101'+digits.slice(0,6).map((n,i)=>parity[i]==='L'?left[n]:invert(left[n]).split('').reverse().join('')).join('')+'01010'+digits.slice(6).map(n=>invert(left[n])).join('')+'101';
 const bars=Array.from('0'.repeat(12)+pattern+'0'.repeat(12)).flatMap(b=>Array(4).fill(b==='1')); 
 await page.addInitScript(({bars})=>{Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d')!;const paint=()=>{ctx.fillStyle='#fff';ctx.fillRect(0,0,640,360);ctx.fillStyle='#000';bars.forEach((bar,x)=>{if(bar&&document.documentElement.dataset.blankCamera!=='yes')ctx.fillRect(70+x,80,1,180);});};paint();const timer=setInterval(paint,50);const stream=canvas.captureStream(20);document.documentElement.dataset.cameraStopped='no';stream.getTracks().forEach(track=>{const stop=track.stop.bind(track);track.stop=()=>{clearInterval(timer);document.documentElement.dataset.cameraStopped='yes';stop();};});return stream;}});},{bars});
 await known(page,false);await openScanner(page);await page.getByRole('button',{name:'Start camera'}).click();await expect(page.getByLabel('Title *',{exact:true})).toHaveValue('Hazelnut spread',{timeout:20000});await expect(page.locator('html')).toHaveAttribute('data-camera-stopped','yes');
 await page.evaluate(()=>{document.documentElement.dataset.blankCamera='yes';});await page.getByRole('button',{name:'Scan product'}).click();await page.getByRole('button',{name:'Start camera'}).click();await expect(page.locator('html')).toHaveAttribute('data-camera-stopped','no');await page.getByRole('button',{name:'Close scanner'}).click();await expect(page.locator('html')).toHaveAttribute('data-camera-stopped','yes');
});
test('product endpoints reject invalid codes; installed icons and Apple metadata are served',async({request,page})=>{
 expect((await request.get('/api/products/invalid')).status()).toBe(400);expect((await request.get('/api/products/invalid/image')).status()).toBe(400);const manifest=await(await request.get('/manifest.webmanifest')).json();for(const icon of manifest.icons)expect((await request.get(icon.src)).status()).toBe(200);await page.goto('/');const apple=await page.locator('link[rel="apple-touch-icon"][sizes="180x180"]').getAttribute('href');expect((await request.get(apple!)).headers()['content-type']).toContain('image/png');
});
test('barcode metadata survives server sync and photo failure does not block saving',async({page,request})=>{
 await known(page);await page.route(`**/api/products/${barcode}/image?*`,r=>r.fulfill({status:502}));await openScanner(page);await page.getByLabel('Barcode number').fill(barcode);await page.getByRole('button',{name:'Find product',exact:true}).click();await expect(page.getByLabel('Title *',{exact:true})).toHaveValue('Hazelnut spread');await expect(page.getByText(/photo could not be downloaded/)).toBeVisible();await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.locator('.detail-view')).toContainText('Hazelnut spread');
 const owner=`barcode-${crypto.randomUUID()}`,headers={'X-Memorate-Account':owner,'oai-authenticated-user-id':owner,'oai-authenticated-user-email':'qa@sites.test',Origin:'http://127.0.0.1:4175'};
 const note={id:'barcode-note',title:'Product',barcode,productSource:'open-food-facts',productInfo:{barcode,brand:'Oreo',ingredients:'Wheat',batchNumber:'LOT42',expiryDate:'2027-10-31',sources:['open-food-facts']},comment:'My own review',rating:null,price:null,currency:'EUR',categoryId:null,date:'2026-09-25',createdAt:'',updatedAt:'',photos:[]};const data={notes:[note],categories:[],preferences:{theme:'system',defaultCurrency:'EUR'}};
 expect((await request.post('/api/sync',{headers,data:{revision:0,data}})).status()).toBe(200);const saved=await(await request.get('/api/sync',{headers})).json();expect(saved.data.notes[0]).toEqual(note);
});
test('cancelling while camera permission is pending stops a stream that arrives later',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:()=>new Promise<MediaStream>(resolve=>{document.documentElement.dataset.permissionPending='yes';document.addEventListener('grant-test-camera',()=>{const canvas=document.createElement('canvas');const stream=canvas.captureStream();stream.getTracks().forEach(track=>{const stop=track.stop.bind(track);track.stop=()=>{document.documentElement.dataset.lateCameraStopped='yes';stop();};});resolve(stream);},{once:true});})});});
 await openScanner(page);await page.getByRole('button',{name:'Start camera'}).click();await expect(page.locator('html')).toHaveAttribute('data-permission-pending','yes');await page.getByRole('button',{name:'Close scanner'}).click();await page.evaluate(()=>document.dispatchEvent(new Event('grant-test-camera')));await expect(page.locator('html')).toHaveAttribute('data-late-camera-stopped','yes');
});
test('mobile home quick scan opens directly, prefills non-food product without photo, and never auto-saves',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await page.route('**/api/products/0036000291452?*',r=>r.fulfill({json:{product:{barcode:'0036000291452',name:'Kleenex tissues',source:'upcitemdb',hasImage:false}}}));
 await openScanner(page);await expect(page.getByLabel('Title *',{exact:true})).toBeHidden();await page.getByLabel('Barcode number').fill('00036000291452');await page.getByRole('button',{name:'Find product',exact:true}).click();
 await expect(page.getByLabel('Title *',{exact:true})).toHaveValue('Kleenex tissues');await expect(page.getByText('Found: Kleenex tissues. Review before saving.')).toBeVisible();await expect(page.locator('.photo-edit')).toHaveCount(0);
 await expect(page.locator('.note-card')).toHaveCount(0);await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Discard changes',exact:true}).click();
 await page.getByRole('button',{name:'Add note',exact:true}).click();await expect(page.getByLabel('Title *',{exact:true})).toHaveValue('');await expect(page.getByText(/Barcode:/)).toBeHidden();
});
test('rate limit is distinct from not-found, and unknown products offer retry/manual options',async({page})=>{
 await page.route(`**/api/products/${barcode}?*`,r=>r.fulfill({status:429,headers:{'Retry-After':'60'},json:{error:'rate limit'}}));await openScanner(page);await page.getByLabel('Barcode number').fill(barcode);await page.getByRole('button',{name:'Find product',exact:true}).click();await expect(page.getByRole('alert')).toContainText('busy');await expect(page.getByText('Product not found',{exact:true})).toBeHidden();
 await page.route(`**/api/products/${barcode}?*`,r=>r.fulfill({json:{product:null}}));await page.getByRole('button',{name:'Find product',exact:true}).click();await expect(page.getByText('Product not found',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Enter barcode manually',exact:true}).click();await expect(page.getByLabel('Barcode number')).toBeFocused();
});
test('product info stays separate from Comment; category/price are opt-in and survive saving offline',async({page})=>{
 const info={barcode,originalName:'原始商品',displayName:'Oreo Mini Strawberry',brand:'Oreo',ingredients:'Wheat, cocoa',quantity:'55 g',sources:['open-food-facts']};
 await page.route(`**/api/products/${barcode}?*`,r=>r.fulfill({json:{product:{barcode,name:'Oreo Mini Strawberry',source:'open-food-facts',hasImage:false,productInfo:info,categorySuggestion:'Food',suggestedPrice:{amount:2.49,currency:'EUR',source:'Shop',observedAt:Date.now()}}}}));
 await page.goto('/');await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByLabel('Category',{exact:true}).selectOption({label:'Beauty'});await page.getByLabel('Comment',{exact:true}).fill('My personal opinion');await page.getByRole('button',{name:'Scan product',exact:true}).click();await page.getByLabel('Barcode number').fill(barcode);await page.getByRole('button',{name:'Find product',exact:true}).click();
 await expect(page.getByLabel('Title *',{exact:true})).toHaveValue('Oreo Mini Strawberry');await expect(page.getByLabel('Comment',{exact:true})).toHaveValue('My personal opinion');await expect(page.getByLabel('Category',{exact:true}).locator('option:checked')).toHaveText('Beauty');await expect(page.getByLabel('Price',{exact:true})).toHaveValue('');
 await page.getByRole('button',{name:'Use category',exact:true}).click();await expect(page.getByLabel('Category',{exact:true}).locator('option:checked')).toHaveText('Food');await page.getByRole('button',{name:'Use price',exact:true}).click();await expect(page.getByLabel('Price',{exact:true})).toHaveValue('2.49');await page.getByLabel('Price',{exact:true}).fill('3.00');
 await page.getByRole('button',{name:'Save note',exact:true}).click();await page.locator('.detail-view .product-info summary').click();await expect(page.locator('.detail-view .product-info')).toContainText('Wheat, cocoa');await expect(page.locator('.detail-comment')).toHaveText('Your noteMy personal opinion');
 await page.reload();await page.locator('.note-card').click();await page.locator('.detail-view .product-info summary').click();await expect(page.locator('.detail-view .product-info')).toContainText('原始商品');await expect(page.locator('.detail-facts')).toContainText('€3.00');
});
test('GS1 batch and expiry are local to each package, persist through retry, and never enter provider URLs',async({page})=>{
 let calls=0;const requests:string[]=[];
 await page.route(`**/api/products/${barcode}?*`,r=>{requests.push(r.request().url());calls++;return calls===1?r.fulfill({status:503}):r.fulfill({json:{product:null}});});
 await openScanner(page);await page.getByLabel('Barcode number').fill(`(01)0${barcode}(17)271031(10)LOT42(21)SECRET-SERIAL`);await page.getByRole('button',{name:'Find product',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'Find product',exact:true}).click();await page.getByRole('button',{name:'Enter product manually',exact:true}).click();
 await page.locator('.editor-scroll .product-info summary').click();await expect(page.locator('.editor-scroll .product-info')).toContainText('LOT42');await expect(page.locator('.editor-scroll .product-info')).toContainText('2027-10-31');expect(requests).toHaveLength(2);for(const url of requests){expect(url).not.toContain('LOT42');expect(url).not.toContain('SECRET-SERIAL');}
 await page.getByLabel('Title *',{exact:true}).fill('Package one');await page.getByRole('button',{name:'Save note',exact:true}).click();await page.getByRole('button',{name:'All notes',exact:true}).click();await page.getByRole('button',{name:'Scan product',exact:true}).click();await page.getByLabel('Barcode number').fill(barcode);await page.getByRole('button',{name:'Find product',exact:true}).click();await page.getByRole('button',{name:'Create another note',exact:true}).click();await page.getByRole('button',{name:'Enter product manually',exact:true}).click();await page.locator('.editor-scroll .product-info summary').click();await expect(page.locator('.editor-scroll .product-info')).not.toContainText('LOT42');await expect(page.locator('.editor-scroll .product-info')).not.toContainText('2027-10-31');
});
