import {test,expect} from '@playwright/test';
const origin='http://127.0.0.1:4175';
const time='2026-09-25T10:00:00.000Z';
const note={id:'public-target',title:'Shared coffee',comment:'A lovely stop',rating:4,categoryId:null,date:'2026-09-25',price:3,currency:'EUR',photos:[],createdAt:time,updatedAt:time,barcode:'6901668054715',productInfo:{barcode:'6901668054715',ingredients:'PRIVATE INGREDIENTS'}};
test('public links isolate a snapshot, enforce owner/origin/account, and revoke page and photos immediately',async({browser,request})=>{
 const owner=`share-${crypto.randomUUID()}`,headers={'oai-authenticated-user-id':owner,'oai-authenticated-user-email':'owner@sites.test','X-Memorate-Account':owner,Origin:origin};const ctx=await browser.newContext({extraHTTPHeaders:headers});
 const page=await ctx.newPage();await page.goto('/shared/invalid');const jpg=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=200;canvas.height=200;const c=canvas.getContext('2d')!;c.fillStyle='#a67';c.fillRect(0,0,200,200);return Array.from(new Uint8Array(await (await new Promise<Blob>(resolve=>canvas.toBlob(b=>resolve(b!),'image/jpeg'))).arrayBuffer()));});
 const uploaded=await ctx.request.put('/api/photos/share-photo',{headers:{'Content-Type':'image/jpeg'},data:Buffer.from(jpg)});expect(uploaded.ok()).toBeTruthy();
 const withPhoto={...note,photos:[{id:'share-photo',width:200,height:200,mimeType:'image/jpeg'}]};const secret={...note,id:'private-other',title:'SECRET OTHER NOTE',photos:[]};const body={revision:0,data:{notes:[withPhoto,secret],categories:[],preferences:{theme:'berry',defaultCurrency:'EUR'}}};expect((await ctx.request.post('/api/sync',{data:body})).ok()).toBeTruthy();
 expect((await request.post('/api/shares/public-target',{headers:{Origin:origin},data:{updatedAt:time}})).status()).toBe(401);
 const attacker=await browser.newContext({extraHTTPHeaders:{...headers,'oai-authenticated-user-id':'attacker','X-Memorate-Account':'attacker'}});expect((await attacker.request.post('/api/shares/public-target',{data:{updatedAt:time}})).status()).toBe(404);expect((await ctx.request.post('/api/shares/public-target',{headers:{...headers,Origin:'https://evil.example'},data:{updatedAt:time}})).status()).toBe(403);expect((await ctx.request.post('/api/shares/public-target',{headers:{...headers,'X-Memorate-Account':'someone-else'},data:{updatedAt:time}})).status()).toBe(409);
 expect((await ctx.request.post('/api/shares/public-target',{data:{updatedAt:'2026-09-24T00:00:00.000Z'}})).status()).toBe(409);
 const created=await ctx.request.post('/api/shares/public-target',{data:{updatedAt:time}});expect(created.status()).toBe(201);const {token}=await created.json() as {token:string};expect(token).toMatch(/^[A-Za-z0-9_-]{43}$/);expect((await (await ctx.request.post('/api/shares/public-target',{data:{updatedAt:time}})).json() as {token:string}).token).toBe(token);
 const publicData=await request.get(`/api/shared/${token}`);expect(publicData.ok()).toBeTruthy();const text=await publicData.text();for(const secret of ['PRIVATE INGREDIENTS','SECRET OTHER NOTE','6901668054715','public-target','owner_id',owner,'share-photo'])expect(text).not.toContain(secret);expect(publicData.headers()['cache-control']).toContain('no-store');expect((await request.get(`/api/shared/${token}/photos/0`)).headers()['content-type']).toBe('image/jpeg');expect((await request.get(`/api/shared/${token}/photos/1`)).status()).toBe(404);expect((await request.get('/api/photos/share-photo')).status()).toBe(401);expect((await request.get('/api/sync')).status()).toBe(401);
 const anonymous=await browser.newContext();const pub=await anonymous.newPage();await pub.goto(`/shared/${token}`);await expect(pub.getByRole('heading',{name:'Shared coffee'})).toBeVisible();await expect(pub.getByRole('img')).toBeVisible();expect(await pub.content()).not.toContain('PRIVATE INGREDIENTS');await pub.setViewportSize({width:390,height:844});expect(await pub.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await pub.screenshot({path:'/tmp/memorate-public-note.png',fullPage:true});
 await attacker.request.delete('/api/shares/public-target');expect((await request.get(`/api/shared/${token}`)).status()).toBe(200);
 expect((await ctx.request.delete('/api/shares/public-target')).ok()).toBeTruthy();expect((await request.get(`/api/shared/${token}`)).status()).toBe(404);expect((await request.get(`/api/shared/${token}/photos/0`)).status()).toBe(404);await pub.reload();await expect(pub.getByRole('heading',{name:'This link is no longer available'})).toBeVisible();for(const bad of ['123','a'.repeat(43)])expect((await request.get(`/api/shared/${bad}`)).status()).toBe(404);
 const regenerated=await ctx.request.post('/api/shares/public-target',{data:{updatedAt:time}});expect(regenerated.status()).toBe(201);expect((await regenerated.json() as {token:string}).token).not.toBe(token);await ctx.request.delete('/api/shares/public-target');await anonymous.close();await attacker.close();await ctx.close();
});
test('owner creates and revokes a link through the normal note UI; Settings lists shared snapshots',async({browser})=>{
 const owner=`share-ui-${crypto.randomUUID()}`;const ctx=await browser.newContext({extraHTTPHeaders:{'oai-authenticated-user-id':owner,'oai-authenticated-user-email':'owner@sites.test'}}),p=await ctx.newPage();await p.goto('/');await p.getByRole('button',{name:'New note',exact:true}).click();await p.getByLabel('Title *',{exact:true}).fill('Link from details');await p.getByRole('button',{name:'Save note',exact:true}).click();await p.getByRole('button',{name:'Note actions'}).click();await p.getByRole('menuitem',{name:'Share',exact:true}).click();await p.getByRole('button',{name:'Create public link'}).click();await expect(p.getByLabel('Public link',{exact:true})).toHaveValue(/\/shared\/[\w-]{43}$/);await p.getByRole('dialog',{name:'Share note'}).getByRole('button',{name:'Close',exact:true}).click();await p.getByRole('button',{name:'Settings',exact:true}).click();await expect(p.getByRole('link',{name:'Link from details'})).toBeVisible();await p.getByRole('button',{name:'Revoke link',exact:true}).click();await expect(p.getByText('No public links.',{exact:true})).toBeVisible();await ctx.close();
});
