import { test, expect } from "@playwright/test";
import path from "node:path";
const icon=path.resolve("public/icons/icon-512.png");
test('mobile capture retains every field across photo selection and fits narrow screens',async({page,context})=>{
 await page.setViewportSize({width:320,height:740});await page.goto('/');await expect(page.getByRole('button',{name:'Add your first note'})).toBeVisible();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();
 await page.getByRole('button',{name:'Add your first note'}).click();
 await page.getByLabel('Title *',{exact:true}).fill('Coffee capture');await page.getByRole('button',{name:'4 stars',exact:true}).click();await page.getByLabel('Category',{exact:true}).selectOption('food');await page.getByLabel('Comment',{exact:true}).fill('A good coffee');await page.getByLabel('Price',{exact:true}).fill('12,99');await page.getByLabel('Date',{exact:true}).fill('2026-09-23');
 await page.locator('input[type=file]').setInputFiles(icon);await page.getByRole('button',{name:'Use photo',exact:true}).click();await expect(page.getByRole('dialog',{name:'Adjust photo'})).toBeHidden();
 await expect(page.getByLabel('Title *',{exact:true})).toHaveValue('Coffee capture');await expect(page.getByLabel('Price',{exact:true})).toHaveValue('12,99');await expect(page.getByLabel('Category',{exact:true})).toHaveValue('food');
 await page.getByRole('button',{name:'New category',exact:true}).click();await expect(page.getByLabel('New category name')).toBeVisible();await page.getByRole('button',{name:'New category',exact:true}).click();await expect(page.getByLabel('New category name')).toBeHidden();await expect(page.getByLabel('Category',{exact:true})).toHaveValue('food');
 await page.locator('input[type=file]').setInputFiles([icon,icon]);for(let i=0;i<2;i++)await page.getByRole('button',{name:'Use photo',exact:true}).click();await expect(page.getByRole('dialog',{name:'Adjust photo'})).toBeHidden();
 await page.getByLabel('Comment',{exact:true}).fill('Changed after three photos');await page.locator('input[type=file]').setInputFiles(icon);await page.getByRole('button',{name:'Use photo',exact:true}).click();await expect(page.getByRole('dialog',{name:'Adjust photo'})).toBeHidden();
 for(const width of [320,375,390,430]){await page.setViewportSize({width,height:740});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
 await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByRole('heading',{name:'Coffee capture',exact:true})).toBeVisible();await expect(page.getByText('€12.99',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'All notes',exact:true}).click();await page.getByRole('searchbox').fill('cofee');await expect(page.locator('.note-card')).toHaveCount(1);
 await context.setOffline(true);await page.reload();await expect(page.locator('.note-card')).toHaveCount(1);await page.getByRole('button',{name:'Add note',exact:true}).click();await page.getByLabel('Title *',{exact:true}).fill('Offline note');await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByRole('heading',{name:'Offline note',exact:true})).toBeVisible();await context.setOffline(false);
});
test('backend enforces ownership, CSRF, revisions and object access',async({request})=>{
 const owner=`qa-${crypto.randomUUID()}`,other=`qa-${crypto.randomUUID()}`;const headers={'X-Memorate-Account':owner,'oai-authenticated-user-id':owner,'oai-authenticated-user-email':'qa@sites.test',Origin:'http://127.0.0.1:4175'};
 expect((await request.get('/api/sync')).status()).toBe(401);
 const data={notes:[{id:'n',title:'Private',comment:'',rating:null,price:2.5,currency:'EUR',categoryId:null,date:'2026-09-24',createdAt:'2026-09-24T12:00:00.000Z',updatedAt:'2026-09-24T12:00:00.000Z',photos:[]}],categories:[],preferences:{theme:'dark',defaultCurrency:'EUR'}};
 const rejected=await request.post('/api/sync',{headers:{...headers,Origin:'https://evil.test'},data:{revision:0,data}});expect(rejected.status()).toBe(403);
 expect((await request.post('/api/sync',{headers:{...headers,'X-Memorate-Account':other},data:{revision:0,data}})).status()).toBe(409);
 const saved=await request.post('/api/sync',{headers,data:{revision:0,data}});expect(await saved.json()).toEqual({revision:1});
 const stale=await request.post('/api/sync',{headers,data:{revision:0,data:{...data,notes:[]}}});expect(stale.status()).toBe(409);
 expect((await (await request.get('/api/sync',{headers})).json()).data.notes).toHaveLength(1);
 expect((await (await request.get('/api/sync',{headers:{...headers,'X-Memorate-Account':other,'oai-authenticated-user-id':other}})).json()).data.notes).toHaveLength(0);
 expect((await request.get('/api/photos/missing',{headers:{...headers,'X-Memorate-Account':other,'oai-authenticated-user-id':other}})).status()).toBe(404);
 expect((await request.put('/api/photos/invalid',{headers:{...headers,'Content-Type':'image/jpeg'},data:Buffer.from('not an image')})).status()).toBe(400);
});
test('desktop layout, portable ZIP export and import, unsaved close guard',async({page,browser})=>{
 await page.setViewportSize({width:1280,height:850});await page.goto('/');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await page.getByRole('button',{name:'New note',exact:true}).click();await page.getByLabel('Title *',{exact:true}).fill('Backup example');await page.locator('input[type=file]').setInputFiles(icon);await page.getByRole('button',{name:'Use photo',exact:true}).click();await expect(page.getByRole('dialog',{name:'Adjust photo'})).toBeHidden();await page.getByRole('button',{name:'Save note',exact:true}).click();await page.getByRole('button',{name:'All notes',exact:true}).click();expect(await page.locator('.notes-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length)).toBe(2);
 await page.getByRole('button',{name:'Settings',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export all data (.zip)'}).click();const file=await download;const filePath=await file.path();expect(filePath).toBeTruthy();
 const clean=await browser.newContext();const p=await clean.newPage();await p.goto('/');await p.evaluate(async()=>{await navigator.serviceWorker.ready;});await p.reload();await p.getByRole('button',{name:'Settings',exact:true}).click();await p.locator('input[type=file]').setInputFiles(filePath!);await expect(p.locator('.toast')).toContainText('Backup imported');await p.getByRole('button',{name:'Collection',exact:true}).click();await expect(p.getByRole('heading',{name:'Backup example',exact:true})).toBeVisible();await p.getByRole('button',{name:'New note',exact:true}).click();await p.getByLabel('Title *',{exact:true}).fill('Unsaved');await p.getByRole('button',{name:'Close',exact:true}).click();await expect(p.getByRole('alertdialog')).toContainText('Discard unsaved changes');await p.getByRole('button',{name:'Keep editing'}).click();await expect(p.getByLabel('Title *',{exact:true})).toHaveValue('Unsaved');await clean.close();
});
test('two browser devices sync photos, offline edits and deletes without sharing with another owner',async({browser})=>{
 const user=`device-${crypto.randomUUID()}`;const headers={'oai-authenticated-user-id':user,'oai-authenticated-user-email':'qa@sites.test'};
 const a=await browser.newContext({extraHTTPHeaders:headers}),b=await browser.newContext({extraHTTPHeaders:headers});const p=await a.newPage(),q=await b.newPage();
 await p.goto('/');await p.evaluate(async()=>{await navigator.serviceWorker.ready;});await p.reload();await p.getByRole('button',{name:'New note',exact:true}).click();await p.getByLabel('Title *',{exact:true}).fill('Cloud photo');await p.locator('input[type=file]').setInputFiles(icon);await p.getByRole('button',{name:'Use photo',exact:true}).click();await expect(p.getByRole('dialog',{name:'Adjust photo'})).toBeHidden();await p.getByRole('button',{name:'Save note',exact:true}).click();await p.getByRole('button',{name:'Settings',exact:true}).click();await p.getByRole('button',{name:'Enable cloud backup',exact:true}).click();await expect(p.getByText('Cloud backup is up to date',{exact:true})).toBeVisible();
 await q.goto('/');await q.evaluate(async()=>{await navigator.serviceWorker.ready;});await q.reload();await q.getByRole('button',{name:'Settings',exact:true}).click();await q.getByRole('button',{name:'Enable cloud backup',exact:true}).click();await expect(q.getByText('Cloud backup is up to date',{exact:true})).toBeVisible();await q.getByRole('button',{name:'Collection',exact:true}).click();await expect(q.getByRole('heading',{name:'Cloud photo',exact:true})).toBeVisible();await q.locator('.note-card').click();await expect(q.getByRole('img',{name:'Cloud photo, photo 1'})).toBeVisible();
 await b.setOffline(true);await q.getByRole('button',{name:'Note actions',exact:true}).click();await q.getByRole('menuitem',{name:'Edit note',exact:true}).click();await q.getByLabel('Title *',{exact:true}).fill('Edited offline');await q.getByRole('button',{name:'Save changes',exact:true}).click();await b.setOffline(false);await q.getByRole('button',{name:'Settings',exact:true}).click();await q.getByRole('button',{name:'Sync now',exact:true}).click();await expect(q.getByText('Cloud backup is up to date',{exact:true})).toBeVisible();
 await p.getByRole('button',{name:'Sync now',exact:true}).click();await expect(p.getByText('Cloud backup is up to date',{exact:true})).toBeVisible();await p.getByRole('button',{name:'Collection',exact:true}).click();await expect(p.getByRole('heading',{name:'Edited offline',exact:true})).toBeVisible();
 await q.getByRole('button',{name:'Collection',exact:true}).click();await q.locator('.note-card').click();await b.setOffline(true);await q.getByRole('button',{name:'Note actions',exact:true}).click();await q.getByRole('menuitem',{name:'Delete note',exact:true}).click();await q.getByRole('button',{name:'Delete note',exact:true}).click();await b.setOffline(false);await q.getByRole('button',{name:'Settings',exact:true}).click();await q.getByRole('button',{name:'Sync now',exact:true}).click();await expect(q.getByText('Cloud backup is up to date',{exact:true})).toBeVisible();await p.getByRole('button',{name:'Settings',exact:true}).click();await p.getByRole('button',{name:'Sync now',exact:true}).click();await expect(p.getByText('Cloud backup is up to date',{exact:true})).toBeVisible();await p.getByRole('button',{name:'Collection',exact:true}).click();await expect(p.locator('.note-card')).toHaveCount(0);
 await a.close();await b.close();
});
test('real touch swipes reveal actions, dismiss below threshold and preserve vertical scroll',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage();await page.goto('/');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();
 await page.getByRole('button',{name:'Add note',exact:true}).click();await page.getByLabel('Title *',{exact:true}).fill('Swipe me');await page.getByRole('button',{name:'Save note',exact:true}).click();await page.getByRole('button',{name:'All notes',exact:true}).click();
 const cdp=await context.newCDPSession(page);const box=(await page.locator('.note-card').boundingBox())!;
 async function swipe(dx:number){const x=box.x+box.width-20,y=box.y+box.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/8,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 await swipe(-40);await expect(page.locator('.swipe-actions')).toHaveAttribute('aria-hidden','true');await expect(page.locator('.swipe-surface')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');await swipe(-180);await expect(page.locator('.swipe-actions')).toHaveAttribute('aria-hidden','false');await page.getByRole('button',{name:'Edit',exact:true}).click();await expect(page.getByRole('heading',{name:'Edit note',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Filters and sort',exact:true}).click();await expect(page.getByLabel('From date')).toBeVisible();await expect(page.getByLabel('To date')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await context.close();
});
test('pull refresh thresholds, vertical scrolling and detail return preserve the feed',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage();await page.goto('/');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();
 const cdp=await context.newCDPSession(page);
 async function drag(x:number,y:number,dy:number){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+dy*i/12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 const blank=(await page.locator('.empty-state').boundingBox())!;await drag(blank.x+15,blank.y+50,70);await expect(page.locator('.toast')).toHaveCount(0);await drag(blank.x+15,blank.y+50,200);await expect(page.locator('.toast')).toHaveText('Collection refreshed');
 for(let i=0;i<7;i++){await page.getByRole('button',{name:'Add note',exact:true}).click();await page.getByLabel('Title *',{exact:true}).fill(`Memory ${i}`);await page.getByRole('button',{name:'Save note',exact:true}).click();await page.getByRole('button',{name:'All notes',exact:true}).click();}
 const box=(await page.locator('.note-card').first().boundingBox())!;await drag(box.x+100,box.y+110,-180);await expect.poll(()=>page.evaluate(()=>scrollY)).toBeGreaterThan(0);await page.reload();await expect(page.locator('.note-card')).toHaveCount(7);await page.evaluate(()=>scrollTo(0,500));const before=await page.evaluate(()=>scrollY);await page.locator('.note-card').nth(3).click();await page.getByRole('button',{name:'All notes',exact:true}).click();expect(Math.abs((await page.evaluate(()=>scrollY))-before)).toBeLessThan(3);await context.close();
});
