"use client";
import { useRef, useState } from "react";
import { exportBackup, importBackup } from "@/lib/backup";
import type { SyncStatus } from "@/hooks/use-cloud-sync";

export function DataSettings({onChange,onNotice,syncStatus,onSync}:{onChange:()=>Promise<void>;onNotice:(message:string)=>void;syncStatus:SyncStatus;onSync:()=>Promise<void>}){
 const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 const {session,syncedAt}=syncStatus;
 const status={local:"Local only",pending:"Changes waiting to sync",syncing:"Your notes are saved on this device.",synced:"Cloud backup is up to date",offline:"Offline · Changes will sync when connected",error:"Sync error · Local notes are safe"}[syncStatus.phase];
 async function backup(){setBusy(true);try{const blob=await exportBackup(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`memorate-${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);onNotice("Backup exported");}catch(e){onNotice(e instanceof Error?e.message:"Export failed");}finally{setBusy(false);}}
 async function restore(file:File){setBusy(true);try{await importBackup(file);await onChange();onNotice("Backup imported. Existing notes were preserved.");}catch(e){onNotice(e instanceof Error?e.message:"Invalid backup; nothing changed.");}finally{setBusy(false);}}
 return <><section className="settings-section"><h2>Your data</h2><p className="section-note">Your collection belongs to you. Notes and photos remain available on this device offline. Export a complete backup before clearing browser data or changing devices.</p><div className="backup-actions"><button className="secondary-button" disabled={busy} onClick={backup}>Export all data (.zip)</button><button className="secondary-button" disabled={busy} onClick={()=>input.current?.click()}>Import backup</button></div><input ref={input} type="file" hidden accept=".zip,.json" onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value="";if(file)void restore(file);}}/><p className="section-note">Import merges notes and photos without replacing existing data. Appearance and currency are restored when your collection is empty. Backups are not encrypted; keep them somewhere private.</p></section>
 <section className="settings-section"><h2>Account & sync</h2>{session.user?<><p className="section-note">Signed in as {session.user.name}</p><button className="secondary-button" disabled={busy||syncStatus.phase==="syncing"} onClick={onSync}>{syncStatus.phase==="syncing"?"Syncing…":"Sync now"}</button><a className="text-button" href="/signout-with-chatgpt?return_to=%2F" target="_top">Sign out</a></>:<><p className="section-note">Use Memorate locally without an account. Signing in automatically merges this collection with your private cloud backup and syncs your devices.</p><a className="secondary-button" href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a></>}<p className="section-note" role="status">{status}</p>{syncStatus.phase==="error"&&<p className="section-note">{syncStatus.error}</p>}{syncedAt&&<p className="section-note">Last synced: {new Date(syncedAt).toLocaleString()}</p>}</section><p className="version">Memorate · Version 1.2 · Local-first</p></>;
}
