"use client";
import { useEffect, useRef, useState } from "react";
import { exportBackup, importBackup } from "@/lib/backup";
import { authProvider, syncService, type Session } from "@/lib/sync";
import { repository } from "@/lib/repository";
export function DataSettings({onChange,onNotice}:{onChange:()=>Promise<void>;onNotice:(message:string)=>void}){
 const [session,setSession]=useState<Session>({user:null}),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState("Stored on this device"),[syncedAt,setSyncedAt]=useState("");const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{void authProvider.session().then(setSession).catch(()=>{});void repository.syncMetadata().then(meta=>{setEnabled(!!meta);setSyncedAt(meta?.syncedAt||"");if(meta)setStatus("Stored on this device · Cloud backup enabled");});},[]);
 async function sync(){setBusy(true);setStatus("Synchronizing…");try{const result=await syncService.sync();setEnabled(true);setSyncedAt(new Date().toISOString());setStatus(result.conflicts?`${result.conflicts} conflicting edits preserved as recovered copies`:result.pending?"Recent local changes are waiting for the next sync":"Cloud backup is up to date");await onChange();}catch(e){setStatus(e instanceof Error?e.message:"Sync failed; local notes are safe.");}finally{setBusy(false);}}
 async function backup(){setBusy(true);try{const blob=await exportBackup(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`memorate-${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);onNotice("Backup exported");}catch(e){onNotice(e instanceof Error?e.message:"Export failed");}finally{setBusy(false);}}
 async function restore(file:File){setBusy(true);try{await importBackup(file);await onChange();onNotice("Backup imported. Existing notes were preserved.");}catch(e){onNotice(e instanceof Error?e.message:"Invalid backup; nothing changed.");}finally{setBusy(false);}}
 return <><section className="settings-section"><h2>Your data</h2><p className="section-note">Your collection belongs to you. Notes and photos remain available on this device offline. Export a complete backup before clearing browser data or changing devices.</p><div className="backup-actions"><button className="secondary-button" disabled={busy} onClick={backup}>Export all data (.zip)</button><button className="secondary-button" disabled={busy} onClick={()=>input.current?.click()}>Import backup</button></div><input ref={input} type="file" hidden accept=".zip,.json" onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value="";if(file)void restore(file);}}/><p className="section-note">Import merges notes and photos without replacing existing data. Appearance and currency are restored when your collection is empty. Backups are not encrypted; keep them somewhere private.</p></section>
 <section className="settings-section"><h2>Account & sync</h2>{session.user?<><p className="section-note">Signed in as {session.user.name}</p><button className="secondary-button" disabled={busy} onClick={sync}>{busy?"Working…":enabled?"Sync now":"Enable cloud backup"}</button><a className="text-button" href="/signout-with-chatgpt?return_to=%2F" target="_top">Sign out</a></>:<><p className="section-note">Start locally without an account. Sign in to enable private cloud backup and use your collection on another device.</p><a className="secondary-button" href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a></>}<p className="section-note" role="status">{status}</p>{syncedAt&&<p className="section-note">Last synced: {new Date(syncedAt).toLocaleString()}</p>}</section><p className="version">Memorate · Version 1.1 · Local-first</p></>;
}
