"use client";
/* eslint-disable @next/next/no-img-element -- Locally generated poster preview. */
import {z} from 'zod';
import {useEffect,useState,useRef} from 'react';
import {Download,Image as ImageIcon,Link,Share2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import type {Note,Category} from '@/lib/models';
import {authProvider,syncService} from '@/lib/sync';
import {shareTokenSchema} from '@/lib/public-note';
import {createNoteImage} from '@/lib/share-image';
import {THEMES,type Palette,type ThemePreference} from '@/lib/themes';
export async function shareRequest(path:string,owner:string,method='GET',body?:unknown){const response=await fetch(path,{method,cache:'no-store',headers:{'X-Memorate-Account':owner,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=z.object({error:z.string().optional(),token:shareTokenSchema.nullable().optional(),revoked:z.boolean().optional(),shares:z.array(z.object({noteId:z.string(),token:shareTokenSchema,title:z.string()})).optional()}).parse(await response.json());if(!response.ok)throw new Error(data.error||'Sharing is unavailable. Try again.');return data;}
export function ShareNote({note,category,onClose}:{note:Note;category?:Category;onClose:()=>void}){
 const statusVersion=useRef(0);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[token,setToken]=useState<string|null>(null),[owner,setOwner]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState('');
 useEffect(()=>{let active=true;const version=++statusVersion.current;authProvider.session().then(async({user})=>{if(user){const data=await shareRequest(`/api/shares/${note.id}`,user.id);if(active&&version===statusVersion.current){setOwner(user.id);setToken(data.token?shareTokenSchema.parse(data.token):null);}}}).catch(()=>{/* Image sharing remains available offline. */});return()=>{active=false;};},[note.id]);
 // Own and release the browser resource for this generated file.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!file)return;const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function run(work:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await work();}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Unable to share. Try again.');}finally{setBusy(false);}}
 const link=token?`${location.origin}/shared/${token}`:'';
 async function createLink(){statusVersion.current++;const {user}=await authProvider.session();if(!user)throw new Error('Sign in through Settings to create a public link. Image sharing works offline.');await syncService.sync();const data=await shareRequest(`/api/shares/${note.id}`,user.id,'POST',{updatedAt:note.updatedAt});setOwner(user.id);setToken(shareTokenSchema.parse(data.token));setMessage('Link created. Only this shared copy is included.');}
 async function image(){const key=document.documentElement.dataset.theme as Exclude<ThemePreference,'system'>;const p:Palette=(THEMES[key]||THEMES.light).palette;setFile(new File([await createNoteImage(note,category,p)],'memorate-note.png',{type:'image/png'}));}
 async function sendImage(){if(file&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:note.title});else download();}
 function download(){if(!preview)return;const a=document.createElement('a');a.href=preview;a.download='memorate-note.png';a.click();setMessage('Image ready to save.');}
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="share-dialog"><DialogTitle>Share note</DialogTitle><DialogDescription>Share your review, category, rating and photos. Product Info and barcode stay private.</DialogDescription><div className="share-choices"><button className="secondary-button" disabled={busy} onClick={()=>void run(image)}><ImageIcon size={19}/>Share as image</button><button className="secondary-button" disabled={busy} onClick={()=>void run(createLink)}><Link size={19}/>{token?'Keep current link':'Create public link'}</button></div>{busy&&<p role="status">Preparing…</p>}{file&&preview&&<div className="share-image-result"><img src={preview} alt="Share image preview"/><div className="share-choices"><button className="primary-button" disabled={busy} onClick={()=>void run(sendImage)}><Share2 size={18}/>Share image</button><button className="secondary-button" onClick={download}><Download size={18}/>Save image</button></div></div>}{token&&<div className="share-link-result"><label className="field-label" htmlFor="public-note-link">Public link</label><input id="public-note-link" className="field-input" readOnly value={link} onFocus={e=>e.currentTarget.select()}/><p>This is a snapshot. Later edits stay private. Revoke and create a new link to share an updated copy.</p><div className="share-choices"><button className="secondary-button" onClick={()=>void run(async()=>{await navigator.clipboard.writeText(link);setMessage('Link copied');})}>Copy link</button>{typeof navigator.share==='function'&&<button className="secondary-button" onClick={()=>void run(()=>navigator.share({url:link,title:note.title}))}>Share link</button>}<button className="text-button" disabled={busy} onClick={()=>void run(async()=>{statusVersion.current++;await shareRequest(`/api/shares/${note.id}`,owner,'DELETE');setToken(null);setMessage('Link revoked');})}>Revoke link</button></div></div>}{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>;
}
export function SharedLinks({owner}:{owner?:string}){
 const [links,setLinks]=useState<{noteId:string;token:string;title:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 useEffect(()=>{let active=true;if(owner)shareRequest('/api/shares',owner).then(data=>{if(active)setLinks(data.shares||[]);}).catch(()=>{if(active)setError('Unable to load shared links.');});return()=>{active=false;};},[owner]);
 if(!owner)return null;
 return <section className="settings-section"><h2>Shared links</h2><p className="section-note">Only notes you explicitly share are public. Revoke access here, even after removing a local note.</p>{error&&<p role="alert">{error}</p>}{!links.length&&!error&&<p className="section-note">No public links.</p>}{links.map(link=><div className="shared-link-row" key={link.noteId}><a href={`/shared/${link.token}`} target="_blank" rel="noreferrer">{link.title}</a><button className="text-button" disabled={!!busy} onClick={async()=>{setBusy(link.noteId);setError('');try{await shareRequest(`/api/shares/${link.noteId}`,owner,'DELETE');setLinks(old=>old.filter(v=>v.noteId!==link.noteId));}catch{setError('Could not revoke the link. Try again.');}finally{setBusy('');}}}>Revoke link</button></div>)}</section>;
}
